import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Dict, List


DEFAULT_INPUT = (
    Path(__file__).resolve().parent
    / "generated_prompts"
    / "eval_prompts.tlcodesum-funcom.n150.seed42.jsonl"
)
DEFAULT_OUTPUT_DIR = Path(__file__).resolve().parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Split prompt records by system_name and convert them to batch request jsonl files."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=DEFAULT_INPUT,
        help="Input prompt jsonl generated by generate_eval_prompts.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory to write per-system batch request files.",
    )
    parser.add_argument(
        "--model",
        default="qwen3-max",
        help="Model name written into the request body.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0,
        help="Temperature written into the request body.",
    )
    parser.add_argument(
        "--url",
        default="/v1/chat/completions",
        help="Request URL path.",
    )
    return parser.parse_args()


def slugify_system_name(name: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9._-]+", "_", name.strip())
    return slug.strip("._-") or "system"


def load_prompt_records(path: Path) -> List[dict]:
    records = []
    with path.open("r", encoding="utf-8") as file:
        for line in file:
            line = line.strip()
            if not line:
                continue
            records.append(json.loads(line))
    return records


def build_request_record(custom_id: int, prompt_record: dict, model: str, temperature: float, url: str) -> dict:
    return {
        "custom_id": str(custom_id),
        "method": "POST",
        "url": url,
        "body": {
            "model": model,
            "temperature": temperature,
            "messages": [
                {
                    "role": "user",
                    "content": prompt_record["prompt"],
                }
            ],
        },
    }


def write_request_files(
    records_by_system: Dict[str, List[dict]],
    output_dir: Path,
    model: str,
    temperature: float,
    url: str,
) -> List[Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    written_paths = []

    for system_name, prompt_records in sorted(records_by_system.items()):
        output_path = output_dir / f"{slugify_system_name(system_name)}.jsonl"
        with output_path.open("w", encoding="utf-8") as file:
            for custom_id, prompt_record in enumerate(prompt_records):
                request_record = build_request_record(
                    custom_id=custom_id,
                    prompt_record=prompt_record,
                    model=model,
                    temperature=temperature,
                    url=url,
                )
                file.write(json.dumps(request_record, ensure_ascii=False) + "\n")
        written_paths.append(output_path)

    return written_paths


def main() -> None:
    args = parse_args()
    prompt_records = load_prompt_records(args.input)

    records_by_system: Dict[str, List[dict]] = defaultdict(list)
    for record in prompt_records:
        system_name = record.get("system_name")
        if not system_name:
            raise ValueError("Each input record must contain system_name.")
        records_by_system[system_name].append(record)

    written_paths = write_request_files(
        records_by_system=records_by_system,
        output_dir=args.output_dir,
        model=args.model,
        temperature=args.temperature,
        url=args.url,
    )

    for path in written_paths:
        print(f"Saved: {path}")


if __name__ == "__main__":
    main()
